-- ===================================================================================
-- 1. Create public.installers (Lookup Table)
-- ===================================================================================

CREATE TABLE public.installers (
  installer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  acc_number text NULL,
  is_active boolean NOT NULL DEFAULT TRUE,
  first_name text NULL,
  last_name text NULL,
  company_name text NULL,
  phone_number text NULL,
  wcb_number text NULL,
  has_first_aid boolean NULL,
  has_insurance boolean NULL,
  gst_number text NULL,
  street_address text NULL,
  city text NULL,
  zip_code text NULL,
  email text NULL,
  notes text NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);


-- ===================================================================================
-- 2. Create public.installation (Child Table)
--    The job_ref is removed as requested.
-- ===================================================================================

CREATE TABLE public.installation (
  installation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installer_id bigint NULL,
  installation_notes text NULL,
  wrap_date date NULL,
  has_shipped boolean NOT NULL DEFAULT FALSE,
  installation_date date NULL,
  installation_completed timestamptz NULL,
  inspection_date date NULL,
  inspection_completed timestamptz NULL,
  legacy_ref text NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Foreign Key to installers
ALTER TABLE public.installation
  ADD CONSTRAINT fk_installer
  FOREIGN KEY (installer_id)
  REFERENCES public.installers(installer_id)
  ON DELETE SET NULL;


-- ===================================================================================
-- 3. Update public.jobs (Parent Table) to link to installation
-- ===================================================================================

-- Add the Foreign Key column to jobs. The UNIQUE constraint enforces the 1:1 relationship.
ALTER TABLE public.jobs
  ADD COLUMN installation_id bigint UNIQUE NULL;

-- Add the Foreign Key constraint from jobs to installation
ALTER TABLE public.jobs
  ADD CONSTRAINT fk_installation_id
  FOREIGN KEY (installation_id)
  REFERENCES public.installation(installation_id)
  ON DELETE SET NULL; -- If the installation record is deleted, the link in jobs is cleared

---

-- ===================================================================================
-- 4. Trigger Setup for Automatic Record Creation (Two-Step Logic)
-- ===================================================================================

-- Create the trigger function
CREATE OR REPLACE FUNCTION public.handle_new_job_installation()
RETURNS TRIGGER AS $$
DECLARE
  new_install_id bigint;
BEGIN
  -- Step 1: Insert a new row into the installation table and capture its generated ID
  INSERT INTO public.installation (installer_id, has_shipped)
  VALUES (NULL, FALSE)
  RETURNING installation_id INTO new_install_id;

  -- Step 2: Update the newly created jobs record to link the installation ID
  -- This UPDATE is performed on the *newly inserted* job record (identified by NEW.id)
  UPDATE public.jobs
  SET installation_id = new_install_id
  WHERE id = NEW.id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create the trigger on the 'jobs' table
CREATE OR REPLACE TRIGGER trg_create_installation_record
AFTER INSERT ON public.jobs
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_job_installation();