-- 1. Create the Purchase Tracking Table
CREATE TABLE public.purchase_tracking (
    purchase_check_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE UNIQUE,
    
    -- Doors
    doors_ordered_at timestamptz,
    doors_received_at timestamptz,
    
    -- Glass
    glass_ordered_at timestamptz,
    glass_received_at timestamptz,
    
    -- Handles
    handles_ordered_at timestamptz,
    handles_received_at timestamptz,
    
    -- Accessories (Acc)
    acc_ordered_at timestamptz,
    acc_received_at timestamptz,
    
    -- Metadata
    purchasing_comments text,
    updated_at timestamptz DEFAULT now()
);

-- 2. Create a Trigger Function to auto-generate rows for new Jobs
CREATE OR REPLACE FUNCTION public.handle_new_job_purchasing()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.purchase_tracking (job_id)
  VALUES (new.id);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Attach the Trigger to the Jobs table
CREATE TRIGGER on_job_created_create_purchasing
  AFTER INSERT ON public.jobs
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_job_purchasing();

-- 4. Backfill existing jobs (Important if you have existing data)
INSERT INTO public.purchase_tracking (job_id)
SELECT id FROM public.jobs
WHERE id NOT IN (SELECT job_id FROM public.purchase_tracking);